#!/bin/bash

# Colors
RED="\e[0;91m"
GREEN="\e[0;92m"
BLUE="\e[0;34m"
NC="\e[0m"   # No Color
PATH="${HOME}/CODES"

# ---------------------------
# Usage function
# ---------------------------
usage() {
    echo " Usage:"
    echo "   jinie <traj1> [traj2 ...]"
    echo ""
    echo " Example:"
    echo "   jinie traj.dcd"
    echo "   jinie traj1.dcd traj2.dcd"
    echo
    echo "===================================================="
    echo
    exit 1
}


echo
echo -e "\e[0=90;1m====================================================\e[0;21m"
echo
echo -e "${RED}        █████${GREEN} █████${RED} ██████   █████${GREEN} █████${RED} ██████████"
echo -e "${RED}       ░░███ ${GREEN}░░███ ${RED}░░██████ ░░███ ${GREEN}░░███ ${RED}░░███░░░░░█"
echo -e "${RED}        ░███ ${GREEN} ░███ ${RED} ░███░███ ░███ ${GREEN} ░███ ${RED} ░███  █ ░ "
echo -e "${RED}        ░███ ${GREEN} ░███ ${RED} ░███░░███░███ ${GREEN} ░███ ${RED} ░██████   "
echo -e "${RED}        ░███ ${GREEN} ░███ ${RED} ░███ ░░██████ ${GREEN} ░███ ${RED} ░███░░█   "
echo -e "${RED}  ███   ░███ ${GREEN} ░███ ${RED} ░███  ░░█████ ${GREEN} ░███ ${RED} ░███ ░   █"
echo -e "${RED} ░░████████  ${GREEN} █████${RED} █████  ░░█████${GREEN} █████${RED} ██████████"
echo -e "${RED}  ░░░░░░░░   ${GREEN}░░░░░ ${RED}░░░░░    ░░░░░ ${GREEN}░░░░░ ${RED}░░░░░░░░░░ ${NC}"
echo -e "\e[90;1m----------------------------------------------------\e[0;21m"
echo -e "\e[1;32m       @..@   \e[0;21;2m         ▄▖    ▜     ▘     ▐▘ \e[90;22m ▖ ▄▖▄▖ \e[0m " 
echo -e "\e[1;32m      (----)  \e[0;21;2m         ▌▌▛▌▀▌▐ ▌▌▛▘▌▛▘ ▛▌▜▘ \e[90;22m ▌ ▙▌▚  \e[0m "
echo -e "\e[1;32m     ( >__< ) \e[0;21;2m         ▛▌▌▌█▌▐▖▙▌▄▌▌▄▌ ▙▌▐  \e[90;22m ▙▖▌ ▄▌ \e[0m "
echo -e "\e[1;32m     ^^ ~~ ^^ \e[0;21;2m                 ▄▌           \e[90;22m        \e[0m "                        
echo -e "\e[90;1m====================================================\e[0;21m"
echo

# Trajectory arguments
if [ $# -eq 0 ]; then
    echo ; echo " Error: No trajectory files provided."
    usage
fi

for traj in "$@"; do
    if [ ! -f "$traj" ]; then
        echo ; echo " Error: File not found -> $traj"
        exit 1
    fi
done

inputs=("$@")

if [[ ${#inputs[@]} -eq 0 ]]; then
    echo ; echo " ERROR: You have to select at least one trajectory file." ; echo
    echo "====================================================" ; echo
    exit 1
fi

# Inspectation of extensions
first_ext="${inputs[0]##*.}" # Set standard extension

if [[ "$first_ext" != "dcd" && "$first_ext" != "lammpstraj" ]]; then
    echo ; echo " ERROR: Only supports .dcd or ./lammpstraj." ; echo
    echo "====================================================" ; echo
    exit 1
fi

for f in "${inputs[@]}"; do
    if [[ ! -f "$f" ]]; then
        echo ; echo " ERROR: There is no file.: $f" ; echo
        echo "====================================================" ; echo
        exit 1
    fi

    ext="${f##*.}"
    if [[ "$ext" != "$first_ext" ]]; then
        echo ; echo " ERROR: All of the input files should have the same extension."
        echo " - Standard: .$first_ext"
        echo " - One of the files: $f (.$ext)" ; echo
        echo "====================================================" ; echo
        exit 1
    fi
done

echo
echo "===================================================="
echo
echo -e " \e[0;4m[1]\e[24m Mean Squared Displacement"
echo -e " \e[0;4m[2]\e[24m Non-Gaussian Parameter"
echo -e " \e[0;4m[3]\e[24m Ionic Conductivity"
echo -e " \e[0;4m[4]\e[24m Radial Distribution Function"
echo -e " \e[0;4m[5]\e[24m Self-part van Hove Correlation Function"
echo -e " \e[0;4m[6]\e[24m Hop Function"
echo -e " \e[0;4m[7]\e[24m DCD to Lammps trajectory"
echo -e
echo -e " \e[2;4m[0]\e[24m EXIT\e[22;24m"
echo
echo "===================================================="
echo
read -p " [Enter the property index] : " idx
echo
echo "===================================================="
echo
case $idx in
    1) prop="MSD" ;;
    2) prop="NGP" ;;
    3) prop="ICD" ;;
    4) prop="RDF" ;;
    5) prop="GRT" ;;
    6) prop="HOP" ;;
    7) prop="D2L" ;;
    0) echo " Program ends ..."; echo 
       echo "====================================================" ; echo
       exit 0 
       ;;
    *) echo ; echo " ERROR: Enter the right index." ; echo
       echo "====================================================" ; echo
       exit 1 
       ;;
esac

# Execute file
execfile="${PATH}/JINIE/bin/${prop}"
if [[ ! -x "$execfile" ]]; then
    echo ; echo " ERROR: There is no exec. file or no permission: "
    echo "             $execfile"
    echo ; echo "===================================================="; echo
    exit 1
fi

# log directory
mkdir -p ./log
logfile="log/${prop}.log"

# execute data in log file
start_time=$(date "+%Y-%m-%d %H:%M:%S")
echo "====== $prop Calculation start ======" > "$logfile"
echo "Start   : $start_time" >> "$logfile"
echo "Inputs  : ${inputs[*]}" >> "$logfile"
echo "===================================" >> "$logfile"

# EXECUTE
echo 
nohup "$execfile" "${inputs[@]}" >> "$logfile" 2>&1 &
pid=$!

echo " Program : $prop"
echo " PID     : $pid"
echo " Log     : $logfile"
echo 
echo "===================================================="

